use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :blockchain_balance, BlockchainBalanceWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime


config :blockchain_balance,
    coins: 
        %{
        "BTC" => %{
            "api" => "https://test-insight.bitpay.com/api",
            "decimal" => 8,
        },
        "LTC" => %{
            "api" => "https://testnet.litecore.io/api",
            "decimal" => 8,
        },
        "DASH" => %{
            "api" => "https://testnet-insight.dashevo.org/insight-api-dash",
            "decimal" => 8,
        },
        "BCH" => %{
            "api" => "https://test-bch-insight.bitpay.com/api",
            "decimal" => 8,
        },
        "ETH" => %{
            "api" => "https://rinkeby.infura.io/v3/2294f3b338ad4524aa9186012810e412",
            "blockscout_api" => "https://blockscout.com/eth/rinkeby/api",
            "decimal" => 18
        },
        "VET" => %{
            "api" => "https://sync-testnet.vechain.org",
            "api_tokens" => "https://tokenbalancerinkeby.herokuapp.com/api/balance",
            "veforge_api" => "https://testnet.veforge.com/api",
            "decimal" => 18,
            "energy_ticker" => "VTHO",
            "energy_decimal" => 18,
            "assets" => [
                %{
                    "symbol"=> "VTHO",
                    "hash"=>"0x0000000000000000000000000000456e65726779",
                    "decimal" => 18
                },                                                                              
            ]
        }, 
        "NEO" => %{
            "api" => "http://neoscan.mywish.io/api/main_net/v1",
            "decimal" => 0,
        },
        "XRP" => %{
            "api" => "https://xrpnode.herokuapp.com/api",
            "node" => "test",
            "decimal" => 6,
        }, 
        "XLM" => %{
            "api" => "https://horizon-testnet.stellar.org",
            "node" => "test",
            "decimal" => 0,
        }, 
        "NANO" => %{
            "api" => "http://35.227.18.245:7076",
            "decimal" => 0,
        },   
        "EOS" => %{
            "api" => "https://api-kylin.eoslaomao.com/v1",
            "decimal" => 0,
        }
    }